### ISSUE TITLE
Name Generator Export Function to Douane Database

### ISSUE THREAD

**Issue by WafflesMcDuff** [eosfrontier/PersonaGenerator#10]
This is a should, as it is a tool desperatly needed by the Figu SL's, to enhance Douane Spel.

Without this tool, Figu's will almost never have a proper Douane Profile. This is not because of the lack of tools, but because of the lack of usability / user friendlyness in the Douane Admin screen to create new people / override cards.

The export function should always override old data linked to that ICCID number.

This would mean there's three buttons to press for the Figu SL to generate a Figu ID. Press Generate for names, Press Export to select the name, Edit the pop-up pane with the proper info, and bleep the card, and press Save.

**Comment by WafflesMcDuff** [comment]
@SulpherStaer Feb 15, 2020 at 12:16 PM
I am working on this now. I've slowly gained energy and willpower to work on this again. Svelte is helping. I expect I can finish this begin June.

-----
@SulpherStaer Sep 2, 2019 at 1:05 PM
Because a large portion of Orthanc will be done after F12 (especially the bits I will require) this project is now set for frontier 13, as F12 is an impossible goal

-----
@WafflesMcDuff Aug 12, 2019 at 12:49 PM
This can begin once watchtower/orthanc is done

**Comment by SulpherStaer** [comment]
This functionality already exists in the current version.
