### ISSUE TITLE
Simple names if API is unavailable

### ISSUE THREAD

**Issue by SulpherStaer** [eosfrontier/PersonaGenerator#8]
Currently the app relies fully on the API to supply names.

A more limited version of name generation can be done when the app is offline, or otherwisely can't reach the API.

Just first name, last name. (And for dugo two last name) on a limited set. This will be unlikely to ever require updating, and allows figus to still generate names, even if internet goes down.

**Comment by SulpherStaer** [comment]
Not simple names. Usurp the entire function. We do not want to rely on the NPM name generator made by thijs, however lovely it was intended.

Name generation needs to be baked into the app. Original reasoning to not do this, was to be able to just update the namelists, without needing to reboot the app. AWS caching invalidates this aproach anyway.

So the names will be baked into the system so that we do not have to access the filesystem (which was the reason for this work by thijs)

**Comment by SulpherStaer** [comment]
NPM name generator can be removed completely, as Orthanc now has an API call that allows file retrieval (or at least its content)

A 'back up' when orthanc is offline is still needed. As names still need to be generated even if these can't be exported.
That means when there is a communication breakdown, the name generator part still functions.

**Comment by WafflesMcDuff** [comment]
This is no longer needed
